### PR TITLE
Create flow for automating byte-buddy version bump

### PR DESCRIPTION
**Pull request by hughsimpson**
Automates bumping byte-buddy versions. Since bumps will, presumably, mostly be triggered off personal forks, it's not possible to push the bot commit directly to the branch. Additionally, without providing a personal access token, it's not possible for the github actions bot to directly trigger the test workflow. So, the flow is a little more convoluted than I'd like, but still feels more streamlined and preserves provenance. I've tested the following flow locally against my own fork:

- Open up a pr to master with an updated `byte-buddy-tag` (eg. https://github.com/hughsimpson/kanela/pull/10)
- The new action will then automatically build byte-buddy with the patch and open a pr corresponding to the bump (c.f https://github.com/hughsimpson/kanela/pull/11)
- Tests can then be triggered by the comment `please rerun tests` -- this gets around the restriction that bot commits can't trigger workflows.

You'll have noticed that the new workflow is failing in this pr.. That's because, by adding the `byte-buddy-tag` file I've triggered the constraint, but the workflow permissions (specifically `pull-requests: write` and `contents: write`) don't take effect until merged. Linked to my fork so you can see that it does, in fact, work once merged :) 

cc @ivantopo @dpsoft thoughts on this? I believe it could be made more streamlined with a personal access token set by  a repo owner, but since I'm not one, this is pretty much the best I think I can do...

### CODE REVIEW

**Comment by hughsimpson** [comment]
@dpsoft any comments on this?

**Review by dpsoft — APPROVED** [review]
@hughsimpson LGTM.

**Comment by hughsimpson** [comment]
Thanks @dpsoft . I don't have perms, could you do the honours? I'll try out out once it's merged so you should see a follow-up with the lib bump 🤞

**Comment by dpsoft** [comment]
@hughsimpson done!

**Pull request merged**
